Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: s3-nkdchck
      BucketEncryption: 
        ServerSideEncryptionConfiguration: 
        - ServerSideEncryptionByDefault:
            SSEAlgorithm: AES256
      VersioningConfiguration:
        Status: Enabled
      Tags:
        - 
          Key: "Environment"
          Value: "s3-nkdchck"