Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: test-first-pipeline-on-aws
      BucketEncryption: 
        ServerSideEncryptionConfiguration: 
        - ServerSideEncryptionByDefault:
            SSEAlgorithm: AES256
      VersioningConfiguration:
        Status: Enabled
      Tags:
        - 
          Key: "Environment"
          Value: "test-first-pipeline-on-aws"